# Generated by Django 4.1.5 on 2023-02-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare_app', '0003_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=200, upload_to='product_images'),
        ),
    ]
